set -euo pipefail

WORK_DIR=""

usage() {
  cat <<'USAGE'
Usage: install-encrypted-vm [--dry-run] [--repo-root PATH]

Install the war VM with a Disko-managed LUKS2 + Btrfs layout.

Options:
  --dry-run         Generate temporary install files and print commands only.
  --repo-root PATH  Repository root to install from. Defaults to $PWD.
  -h, --help        Show this help.
USAGE
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

info() {
  printf '%s\n' "$*"
}

cleanup() {
  if [[ -n "${WORK_DIR:-}" ]]; then
    rm -rf "$WORK_DIR"
  fi
  rm -f /run/war-disko-luks-password 2>/dev/null || true
}

nix_string() {
  local value=$1

  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  value=${value//\$\{/\\\$\{}
  printf '"%s"' "$value"
}

prompt_secret() {
  local prompt=$1
  local value

  printf '%s: ' "$prompt" >&2
  IFS= read -rs value
  printf '\n' >&2
  printf '%s' "$value"
}

validate_repo_root() {
  local value=$1

  [[ -f "$value/flake.nix" ]] || die "repo root does not contain flake.nix: $value"
  [[ -f "$value/install/disko-config.nix" ]] || die "repo root does not contain install/disko-config.nix: $value"
  [[ -f "$value/flake/nixos-configurations.nix" ]] || die "repo root does not contain flake/nixos-configurations.nix: $value"
  [[ "$value" != *[[:space:]]* ]] || die "repo root paths containing whitespace are not supported by this installer"
}

preflight_flake_inputs() {
  local repo_root=$1

  info "Checking flake inputs before destructive install..."

  if ! (
    cd "$repo_root"
    nix --extra-experimental-features nix-command \
      --extra-experimental-features flakes \
      flake check --no-build --no-write-lock-file
  ); then
    cat >&2 <<'PREFLIGHT_ERROR'

error: flake preflight failed before disk formatting.

The live ISO must be able to resolve and fetch missing flake inputs before the
installer can safely continue. Check DNS/networking, then rerun the installer:

  ping -c 3 github.com
  ping -c 3 cache.nixos.org
  resolvectl status

If this machine is intentionally offline, prefetch the flake inputs into the
live ISO Nix store first. Offline installs are not automated by this installer.
PREFLIGHT_ERROR
    exit 1
  fi
}

validate_disk() {
  local disk=$1
  local resolved
  local type

  [[ -e "$disk" ]] || die "target disk does not exist: $disk"
  resolved=$(readlink -f -- "$disk")
  [[ -b "$resolved" ]] || die "target is not a block device: $disk"

  type=$(lsblk -dnro TYPE -- "$resolved")
  [[ "$type" == "disk" ]] || die "target is not a whole disk: $disk"

  if lsblk -nrpo MOUNTPOINTS -- "$resolved" | grep -q '[^[:space:]]'; then
    die "target disk or one of its partitions is mounted; unmount it before installing"
  fi

  printf '%s' "$resolved"
}

partition_path() {
  local disk=$1
  local number=$2

  if [[ "$disk" =~ [0-9]$ ]]; then
    printf '%sp%s' "$disk" "$number"
  else
    printf '%s%s' "$disk" "$number"
  fi
}

select_disk() {
  local -a disks
  local selection
  local candidate

  mapfile -t disks < <(lsblk -dnpo PATH,TYPE | while read -r path type; do
    [[ "$type" == "disk" ]] || continue
    [[ "$path" != /dev/loop* ]] || continue
    [[ "$path" != /dev/sr* ]] || continue
    printf '%s\n' "$path"
  done)

  [[ ${#disks[@]} -gt 0 ]] || die "no whole disks were detected"

  printf '%s\n' "Available install targets:" >&2
  local i=1
  for candidate in "${disks[@]}"; do
    printf '  %s) ' "$i" >&2
    lsblk -dnro PATH,SIZE,MODEL,SERIAL,TRAN -- "$candidate" >&2
    i=$((i + 1))
  done

  while true; do
    printf 'Select target disk by number or path: ' >&2
    IFS= read -r selection

    if [[ "$selection" =~ ^[0-9]+$ ]] && (( selection >= 1 && selection <= ${#disks[@]} )); then
      printf '%s' "${disks[$((selection - 1))]}"
      return
    fi

    if [[ -n "$selection" ]]; then
      printf '%s' "$selection"
      return
    fi

    printf '%s\n' "Selection is required." >&2
  done
}

write_hardware_config() {
  local repo_root=$1
  local disk=$2
  local esp_partition
  local luks_partition
  local esp_uuid
  local luks_uuid
  local btrfs_uuid

  esp_partition=$(partition_path "$disk" 1)
  luks_partition=$(partition_path "$disk" 2)

  udevadm settle

  esp_uuid=$(blkid -s UUID -o value "$esp_partition")
  luks_uuid=$(blkid -s UUID -o value "$luks_partition")
  btrfs_uuid=$(blkid -s UUID -o value /dev/mapper/cryptroot)

  [[ -n "$esp_uuid" ]] || die "could not detect EFI partition UUID from $esp_partition"
  [[ -n "$luks_uuid" ]] || die "could not detect LUKS partition UUID from $luks_partition"
  [[ -n "$btrfs_uuid" ]] || die "could not detect Btrfs UUID from /dev/mapper/cryptroot"

  cat > "$repo_root/hosts/war/hardware-configuration.nix" <<HARDWARE_CONFIG
# Do not modify this file! It was generated by install/install-encrypted-vm.sh.
{ lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "sr_mod"
    "virtio_blk"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices.cryptroot = {
    device = "/dev/disk/by-uuid/$luks_uuid";
    allowDiscards = true;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/$btrfs_uuid";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
      "noatime"
      "ssd"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/$btrfs_uuid";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
      "noatime"
      "ssd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/$btrfs_uuid";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd"
      "noatime"
      "ssd"
    ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/$btrfs_uuid";
    fsType = "btrfs";
    options = [
      "subvol=var"
      "compress=zstd"
      "noatime"
      "ssd"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/$btrfs_uuid";
    fsType = "btrfs";
    options = [
      "subvol=log"
      "nodatacow"
      "noatime"
      "ssd"
    ];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/$esp_uuid";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
HARDWARE_CONFIG
}

write_install_files() {
  local work_dir=$1
  local repo_root=$2
  local disk=$3
  local disk_nix
  local repo_root_nix

  disk_nix=$(nix_string "$disk")
  repo_root_nix=$(nix_string "$repo_root")

  cat > "$work_dir/install-passwords.nix" <<'INSTALL_PASSWORDS'
{ lib, ... }:

let
  rootHash = lib.removeSuffix "\n" (builtins.readFile ./root-password-hash);
  userHash = lib.removeSuffix "\n" (builtins.readFile ./user-password-hash);
in
{
  users.mutableUsers = true;
  users.users.root.hashedPassword = rootHash;
  users.users.r.hashedPassword = userHash;
}
INSTALL_PASSWORDS

  cat > "$work_dir/install-disko.nix" <<INSTALL_DISKO
import (builtins.toPath (${repo_root_nix} + "/install/disko-config.nix")) {
  diskDevice = ${disk_nix};
}
INSTALL_DISKO

  cat > "$work_dir/flake.nix" <<TEMP_FLAKE
{
  description = "Temporary encrypted VM installer wrapper";

  inputs = {
    repo.url = "path:/mnt/etc/nixos";
    nixpkgs.follows = "repo/nixpkgs";
    home-manager.follows = "repo/home-manager";
  };

  outputs = { nixpkgs, home-manager, repo, ... }:
    {
      nixosConfigurations = import (repo.outPath + "/flake/nixos-configurations.nix") {
        inherit nixpkgs home-manager;

        extraModules = [
          ./install-passwords.nix
        ];
      };
    };
}
TEMP_FLAKE
}

dry_run_commands() {
  local work_dir=$1
  local repo_root=$2

  cat <<COMMANDS
Dry run complete. The installer would run:

  install -m 0600 "$work_dir/luks-passphrase" /run/war-disko-luks-password
  disko --mode destroy,format,mount --yes-wipe-all-disks "$work_dir/install-disko.nix"
  normalize target subvolume permissions under /mnt
  generate explicit encrypted hardware config at "$repo_root/hosts/war/hardware-configuration.nix"
  rsync -a --delete "$repo_root/" /mnt/etc/nixos/
  build temporary install wrapper using repo input path:/mnt/etc/nixos
  nixos-install --no-write-lock-file --flake "$work_dir#war" --no-root-passwd
  initialize and validate /mnt/etc/machine-id
  verify an unprivileged target user can execute a program from /nix/store
COMMANDS
}

copy_repo_to_target() {
  local repo_root=$1
  local target=/mnt/etc/nixos

  mkdir -p "$target"
  rsync -a --delete \
    --exclude '/result' \
    --exclude '/result-*' \
    --exclude '/.direnv' \
    --exclude '/.cache' \
    --exclude '/tmp' \
    "$repo_root/" "$target/"
}

initialize_machine_id() {
  local target_root=$1
  local machine_id

  info "Initializing target machine ID..."

  mkdir -p "$target_root/etc"
  rm -f "$target_root/etc/machine-id"
  systemd-machine-id-setup --root="$target_root"

  [[ -f "$target_root/etc/machine-id" ]] || die "target machine ID was not created"
  machine_id=$(tr -d '\n' < "$target_root/etc/machine-id")

  [[ "$machine_id" =~ ^[0-9a-f]{32}$ ]] || die "target machine ID is not a valid 32-character hexadecimal ID"
  [[ "$machine_id" != "00000000000000000000000000000000" ]] || die "target machine ID must not be all zeroes"
}

normalize_target_permissions() {
  local target_root=$1
  local path

  info "Normalizing target subvolume permissions..."

  for path in \
    "$target_root" \
    "$target_root/home" \
    "$target_root/nix" \
    "$target_root/var" \
    "$target_root/var/log"; do
    [[ -d "$path" ]] || die "expected mounted target directory is missing: $path"
    chmod 0755 "$path"
  done
}

validate_target_execution() {
  local target_root=$1
  local target_executable=/nix/var/nix/profiles/system/sw/bin/true

  info "Checking unprivileged access to the target Nix store..."

  if ! chroot --userspec=65534:65534 "$target_root" "$target_executable"; then
    die "an unprivileged target user cannot execute $target_executable; check /nix permissions and mount options"
  fi
}

main() {
  local dry_run=0
  local repo_root=$PWD

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run)
        dry_run=1
        shift
        ;;
      --repo-root)
        [[ $# -ge 2 ]] || die "--repo-root requires a path"
        repo_root=$2
        shift 2
        ;;
      -h | --help)
        usage
        exit 0
        ;;
      *)
        die "unknown argument: $1"
        ;;
    esac
  done

  repo_root=$(cd "$repo_root" && pwd -P)
  validate_repo_root "$repo_root"

  if [[ $dry_run -eq 0 && ${EUID:-$(id -u)} -ne 0 ]]; then
    die "run as root from the NixOS ISO, or use --dry-run"
  fi

  if [[ $dry_run -eq 0 ]]; then
    preflight_flake_inputs "$repo_root"
  fi

  local disk
  local resolved_disk
  local secret
  local secret_repeat
  local final_confirm

  disk=$(select_disk)
  resolved_disk=$(validate_disk "$disk")

  info ""
  info "Selected disk:"
  lsblk -o NAME,PATH,SIZE,MODEL,SERIAL,TYPE,MOUNTPOINTS -- "$resolved_disk"

  secret=$(prompt_secret "Shared LUKS/root/r password")
  [[ -n "$secret" ]] || die "password must not be empty"
  secret_repeat=$(prompt_secret "Repeat shared password")
  [[ "$secret" == "$secret_repeat" ]] || die "passwords do not match"
  secret_repeat=

  info ""
  info "This will permanently erase all data on:"
  info "  $resolved_disk"
  info ""
  info "The disk will be repartitioned, encrypted, formatted, mounted, and installed as NixOS."
  printf 'To continue, type the exact disk path: ' >&2
  IFS= read -r final_confirm
  [[ "$final_confirm" == "$resolved_disk" ]] || die "disk confirmation did not match; aborted"

  WORK_DIR=$(mktemp -d -t war-encrypted-install.XXXXXX)
  chmod 0700 "$WORK_DIR"

  trap cleanup EXIT
  trap 'cleanup; exit 130' INT TERM

  (
    umask 077
    printf '%s\n' "$secret" > "$WORK_DIR/luks-passphrase"
    printf '%s\n' "$secret" | mkpasswd --method=yescrypt --stdin > "$WORK_DIR/root-password-hash"
    printf '%s\n' "$secret" | mkpasswd --method=yescrypt --stdin > "$WORK_DIR/user-password-hash"
    chmod 0600 "$WORK_DIR/luks-passphrase" "$WORK_DIR/root-password-hash" "$WORK_DIR/user-password-hash"
  )
  secret=

  write_install_files "$WORK_DIR" "$repo_root" "$resolved_disk"

  if [[ $dry_run -eq 1 ]]; then
    dry_run_commands "$WORK_DIR" "$repo_root"
    exit 0
  fi

  install -m 0600 "$WORK_DIR/luks-passphrase" /run/war-disko-luks-password
  umask 022
  disko --mode destroy,format,mount --yes-wipe-all-disks "$WORK_DIR/install-disko.nix"
  normalize_target_permissions /mnt
  write_hardware_config "$repo_root" "$resolved_disk"
  copy_repo_to_target "$repo_root"
  nixos-install --no-write-lock-file --flake "$WORK_DIR#war" --no-root-passwd
  initialize_machine_id /mnt
  validate_target_execution /mnt

  info ""
  info "Install complete. Reboot, unlock LUKS with the shared password, then log in as user r."
  info "The full Git checkout is already installed at /etc/nixos."
}

main "$@"
